version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
        - "4200:4200"
    volumes:
        - /app/node_modules
        - .:/app
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "start:server"]
